// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVo7FkvgHGp0A5Q0nAcO2hXS7wua-X9bg',
    appId: '1:319952881811:web:f4b4437a594efd8a5ca566',
    messagingSenderId: '319952881811',
    projectId: 'chat-app-55074',
    authDomain: 'chat-app-55074.firebaseapp.com',
    storageBucket: 'chat-app-55074.appspot.com',
    measurementId: 'G-VEX6NW1CWX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeqfP50dLjup-W4BVJ3Y5vTkWDG151tIQ',
    appId: '1:319952881811:android:a999e67b7b059a155ca566',
    messagingSenderId: '319952881811',
    projectId: 'chat-app-55074',
    storageBucket: 'chat-app-55074.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS04nJKgMPMEUz9koIdZPgXuvyW4-Ie4M',
    appId: '1:319952881811:ios:84955ab425a32f135ca566',
    messagingSenderId: '319952881811',
    projectId: 'chat-app-55074',
    storageBucket: 'chat-app-55074.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDS04nJKgMPMEUz9koIdZPgXuvyW4-Ie4M',
    appId: '1:319952881811:ios:00bfca7cd4961e745ca566',
    messagingSenderId: '319952881811',
    projectId: 'chat-app-55074',
    storageBucket: 'chat-app-55074.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
